### ISSUE TITLE
Grieffing...

### ISSUE THREAD

**Issue by isoz** [GiantQuartz/SkyBlock#100]
Apparently if all island members are offline and someone teleports to their island they can break everything and pvp is enabled...

**Comment by GiantQuartz** [comment]
How do I reproduce this without third party plugins?

**Comment by isoz** [comment]
What my players are doing is setting home in the target island and waiting for the owner to go offline and then teleporting to the island with /home.

Obviously it's logical to have teleport or homes in a skyblock server...

**Comment by isoz** [comment]
This should be top priority, anyone can destroy othe islands... Why does it make the island breakable after all members log off?...

**Comment by GiantQuartz** [comment]
This is not a top priority because it is not caused by SkyBlock but to external plugins. Anyway, I haven't had much time to work on SkyBlock, I will fix this as soon as I can.

**Comment by LeoBdt** [comment]
Any news? any coming fix?

**Comment by GiantQuartz** [comment]
This will be fixed with #121 really soon

**Comment by GiantQuartz** [comment]
You can use c5d0038ecf6cbe35129902b443c205d418ced19c for this now
