### ISSUE TITLE
Internal server error when removing a slapper

### ISSUE THREAD

**Issue by Mohagames205** [GiantQuartz/SkyBlock#113]
Hi

When I remove a slapper I get an internal server error. I looked into the console and I get a SkyBlock error. So I think that SkyBlock is causing this because without the SkyBlock plugin I don't crash when removing a slapper. 
**The error:**
https://ghostbin.com/paste/vqm9m

**Comment by iZeaoGamer** [comment]
That doesn't provide the full error. All it's showing, is the debug errors, nothing else. Show the full error log, and they might be able to fix it. (Depending on what it is). Thank you!

**Comment by Mohagames205** [comment]
Hi, I think you can see the error in this file:



I get ```[Server thread/CRITICAL]: Error: "Call to a member function getName() on null" (EXCEPTION) in "plugins/SkyBlock (7).phar/src/room17/SkyBlock/SkyBlockListener" at line 174```

**full error:**
https://hastebin.com/licayehelu.md

**Comment by iZeaoGamer** [comment]
I’ve never had this issue. What plugins do you have installed that may be causing this? When does this occurr?

**Comment by iZeaoGamer** [comment]
Hmm.. this is odd. What build of this plugin are you using?

**Comment by Mohagames205** [comment]
Hi i'm using 2.2.6 the newest version available on Poggit. 

There are the plugins that I am using:

```
**Plugins (32):**

- Slapper v1.4.2 
- MSpawns v2.2
- economyAPI v5.7.2
- Worlds v2.0.3
- MineReset v3.2.0
- KitUI v1.3.1
- MysteryCrate v7.0.0
- MagicTelePortal v1.3.4 
- PurePerms v1.4.2-c2a
- 1vs1 v1.0.0
- AlwaysSpawn v2.2.4
- Powertools v1.0.0-PRE
- ScoreHud v2.0.0
- StaffChat v1.1.4
- WorldTP v1.2.1
- LessIsMore v1.0.2 
- BlazinJoin v1.1.5
- Drops v1.0.0
- essentialsTP v1.2.1
- SignPortal v1.1.4
- MOTDShuffle v1.1.6
- PerWorldChat v1.8
- BuilderTools v1.1.0
- SkyBlock v2.2.6
- BuycraftPM v0.5.2 
- KDR v1.0.0
- PortalsPE v1.1.1
- PureChat v1.4.11
- FactionsPro v1.3.12 
- BlockSniper v3.2.3
- MyPlot v1.3.8
- GrabBag v2.4.3

```

**Comment by Mohagames205** [comment]
Hi I just wanted to know if there is any update?

**Comment by GiantQuartz** [comment]
I haven't read the source of slapper, it looks like it doesn't set the level of entity. This commit should fix it, I haven't tested it though, let me know if the bug is still happening.

**Comment by isoz** [comment]
You just need to cancel the damage if 
`!$entity instanceof SlapperEntity && !$entity instanceof SlapperHuman`
