### ISSUE TITLE
A crash at generator 

### ISSUE THREAD

**Issue by INSANEIRON** [GiantQuartz/SkyBlock#116]
There’s a huge bug of island generator, it shuts down the plugin

**Comment by GiantQuartz** [comment]
What version of PocketMine-MP are you using?

**Comment by INSANEIRON** [comment]
Latest

**Comment by Shelly7w7** [comment]
Whats the errror

**Comment by GiantQuartz** [comment]
Latest is not the answer I need, what exact version of PocketMine are you using?
