### ISSUE TITLE
Plugin shuts down when using /reload

### ISSUE THREAD

**Issue by ItzJNTZ** [GiantQuartz/SkyBlock#117]
Plugin shuts down when using /reload. Using latest release of the plugin and PocketMine #1722 (1.8.0)

[Server] Server thread/NOTICE Level "is-0.46700900 1548025425" not found
21.01 00:52:34 [Server] Server thread/CRITICAL TypeError: "Argument 5 passed to room17\SkyBlock\isle\IsleManager::openIsle() must be an instance of pocketmine\level\Level, null given, called in phar:///plugins/SkyBlock.phar/src/room17/SkyBlock/provider/json/JSONProvider.php on line 102" (EXCEPTION) in "SkyBlock.phar/src/room17/SkyBlock/isle/IsleManager" at line 132
21.01 00:52:34 [Server] Server thread/DEBUG #0 SkyBlock.phar/src/room17/SkyBlock/provider/json/JSONProvider(102): room17\SkyBlock\isle\IsleManager->openIsle(string is-0.46700900 1548025425, array Array(), boolean 1, string Shelly, NULL , integer 0)
21.01 00:52:34 [Server] Server thread/DEBUG #1 SkyBlock.phar/src/room17/SkyBlock/session/Session(110): room17\SkyBlock\provider\json\JSONProvider->loadIsle(string is-0.46700900 1548025425)
21.01 00:52:34 [Server] Server thread/DEBUG #2 SkyBlock.phar/src/room17/SkyBlock/provider/json/JSONProvider(62): room17\SkyBlock\session\Session->setIsleId(string is-0.46700900 1548025425)
21.01 00:52:34 [Server] Server thread/DEBUG #3 SkyBlock.phar/src/room17/SkyBlock/session/iSession(59): room17\SkyBlock\provider\json\JSONProvider->loadSession(room17\SkyBlock\session\Session object)
21.01 00:52:34 [Server] Server thread/DEBUG #4 SkyBlock.phar/src/room17/SkyBlock/session/Session(44): room17\SkyBlock\session\iSession->__construct(room17\SkyBlock\session\SessionManager object, string xsprinq)
21.01 00:52:34 [Server] Server thread/DEBUG #5 SkyBlock.phar/src/room17/SkyBlock/session/SessionManager(76): room17\SkyBlock\session\Session->__construct(room17\SkyBlock\session\SessionManager object, pocketmine\Player object)
21.01 00:52:34 [Server] Server thread/DEBUG #6 SkyBlock.phar/src/room17/SkyBlock/session/SessionListener(41): room17\SkyBlock\session\SessionManager->openSession(pocketmine\Player object)
21.01 00:52:34 [Server] Server thread/DEBUG #7 src/pocketmine/plugin/MethodEventExecutor(38): room17\SkyBlock\session\SessionListener->onLogin(pocketmine\event\player\PlayerLoginEvent object)
21.01 00:52:34 [Server] Server thread/DEBUG #8 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(room17\SkyBlock\session\SessionListener object, pocketmine\event\player\PlayerLoginEvent object)
21.01 00:52:34 [Server] Server thread/DEBUG #9 src/pocketmine/event/Event(96): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerLoginEvent object)
21.01 00:52:34 [Server] Server thread/DEBUG #10 src/pocketmine/Player(2057): pocketmine\event\Event->call()
21.01 00:52:34 [Server] Server thread/DEBUG #11 src/pocketmine/Player(2041): pocketmine\Player->completeLoginSequence()
21.01 00:52:34 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(115): pocketmine\Player->handleResourcePackClientResponse(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
21.01 00:52:34 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/protocol/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleResourcePackClientResponse(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
21.01 00:52:34 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(99): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
21.01 00:52:34 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
21.01 00:52:34 [Server] Server thread/DEBUG #16 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(99): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
21.01 00:52:34 [Server] Server thread/DEBUG #17 src/pocketmine/Player(3044): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
21.01 00:52:34 [Server] Server thread/DEBUG #18 src/pocketmine/network/mcpe/RakLibInterface(162): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
21.01 00:52:34 [Server] Server thread/DEBUG #19 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string ***.**.**.** (a players ip), raklib\protocol\EncapsulatedPacket object, integer 0)
21.01 00:52:34 [Server] Server thread/DEBUG #20 src/pocketmine/network/mcpe/RakLibInterface(102): raklib\server\ServerHandler->handlePacket()
21.01 00:52:34 [Server] Server thread/DEBUG #21 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()
21.01 00:52:34 [Server] Server thread/DEBUG #22 src/pocketmine/network/mcpe/RakLibInterface(92): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
21.01 00:52:34 [Server] Server thread/DEBUG #23 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
21.01 00:52:34 [Server] Server thread/DEBUG #24 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
21.01 00:52:34 [Server] Server thread/DEBUG #25 src/pocketmine/Server(2278): pocketmine\snooze\SleeperHandler->sleepUntil(double 1548031954.0969)
21.01 00:52:34 [Server] Server thread/DEBUG #26 src/pocketmine/Server(2139): pocketmine\Server->tickProcessor()
21.01 00:52:34 [Server] Server thread/DEBUG #27 src/pocketmine/Server(1715): pocketmine\Server->start()
21.01 00:52:34 [Server] Server thread/DEBUG #28 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
21.01 00:52:34 [Server] Server thread/DEBUG #29 /pmmp_1722_1.8.0.phar(1): require(string phar:///pmmp_1722_1.8.0.phar/src/pocketmine/PocketMine.php)

**Comment by GiantQuartz** [comment]
I don't think I'm ever going to add support for this, I have been trying to fix it but it just messes up more than it is all the internal code.
