### ISSUE TITLE
A huge crash but idk the reason so help

### ISSUE THREAD

**Issue by INSANEIRON** [GiantQuartz/SkyBlock#119]
I have this plugin running in my server and but people plays skyblock, later, it will crash with this code:

[Server thread/CRITICAL]: InvalidArgumentException: "Alias "basic" is already assigned" (EXCEPTION) in "src/pocketmine/level/generator/GeneratorManager" at line 58

[Server thread/DEBUG]: #0 plugins/SkyBlock.phar/src/room17/SkyBlock/generator/IsleGeneratorManager(48): pocketmine\level\generator\GeneratorManager::addGenerator(string room17\SkyBlock\generator\presets\BasicIsland, string basic)

[Server thread/DEBUG]: #1 plugins/SkyBlock.phar/src/room17/SkyBlock/SkyBlock(71): room17\SkyBlock\generator\IsleGeneratorManager->__construct(room17\SkyBlock\SkyBlock object)

[Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginBase(123): room17\SkyBlock\SkyBlock->onEnable()

[Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(587): pocketmine\plugin\PluginBase->setEnabled(boolean 1)

[Server thread/DEBUG]: #4 src/pocketmine/Server(2003): pocketmine\plugin\PluginManager->enablePlugin(room17\SkyBlock\SkyBlock object)

[Server thread/DEBUG]: #5 src/pocketmine/Server(1989): pocketmine\Server->enablePlugin(room17\SkyBlock\SkyBlock object)

[Server thread/DEBUG]: #6 src/pocketmine/Server(2073): pocketmine\Server->enablePlugins(integer 1)

[Server thread/DEBUG]: #7 src/pocketmine/command/defaults/ReloadCommand(49): pocketmine\Server->reload()

[Server thread/DEBUG]: #8 src/pocketmine/command/SimpleCommandMap(261): pocketmine\command\defaults\ReloadCommand->execute(pocketmine\command\ConsoleCommandSender object, string reload, array Array())

[Server thread/DEBUG]: #9 src/pocketmine/Server(2030): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\command\ConsoleCommandSender object, string reload SkyBlock)

[Server thread/DEBUG]: #10 src/pocketmine/Server(1615): pocketmine\Server->dispatchCommand(pocketmine\command\ConsoleCommandSender object, string reload SkyBlock)

[Server thread/DEBUG]: #11 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\Server->pocketmine\{closure}()

[Server thread/DEBUG]: #12 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()

[Server thread/DEBUG]: #13 src/pocketmine/Server(2349): pocketmine\snooze\SleeperHandler->sleepUntil(double 1548064403.8649)

[Server thread/DEBUG]: #14 src/pocketmine/Server(2209): pocketmine\Server->tickProcessor()

[Server thread/DEBUG]: #15 src/pocketmine/Server(1785): pocketmine\Server->start()

[Server thread/DEBUG]: #16 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gs-40416/, string /home/gs-40416/plugins/)

[Server thread/DEBUG]: #17 (1): require(string phar:///home/gs-40416/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

[INFO] Disabling SkyBlock v2.2.7

[INFO] [SkyBlock] SkyBlock was disabled

**Comment by GiantQuartz** [comment]
`Alias "basic" is already assigned`: It appears that you are using two different plugins registering a generator with the name `basic` (one of them is SkyBlock), you might have to remove something from your plugins folder x)
