### ISSUE TITLE
Sleeping in a bed causes unexpected behavior

### ISSUE THREAD

**Issue by Shelly7w7** [GiantQuartz/SkyBlock#126]
Let's say X is a player.

X makes an Island, craft/buys a bed. Sleep on it and after waking up he manages to disband the island. Then after the cooldown is over he makes a new island, by accident he fells in lava and dies. He spawns back to his old island as he slept on the bed (Sleeping on bed changes the spawn point for the player). As being a developer I have fixed this by canceling the bed event. But you should fix it for other non developer players/Server owners.

**Comment by GiantQuartz** [comment]
Why don't you open a PR?
