### ISSUE TITLE
{Suggestion} World Management.

### ISSUE THREAD

**Issue by AlexPads** [GiantQuartz/SkyBlock#128]
I'm not sure if this would be possible but my suggestion is to save all the worlds in one Big folder inside the world folder so that when we do /worlds or something or we have to edit another world file we don't have to scroll through hours of folders. Otherwise Great Plugin! ♥

**Comment by GiantQuartz** [comment]
This is a great idea, but it would cause BC problems. I won't do it for now, thanks for the suggestion though!

**Comment by AlexPads** [comment]
Bc Problems? what that not shortened xD and ok it was just a suggestion so 😂
