### ISSUE TITLE
Tried to close a level which is already closed

### ISSUE THREAD

**Issue by FaanMaario** [GiantQuartz/SkyBlock#132]
Hi, we have this error sometimes and we don't know why it happens

`PocketMine-MP Crash Dump Wed Mar 6 22:50:09 CET 2019

Error: Tried to close a level which is already closed
File: src/pocketmine/level/Level
Line: 468
Type: InvalidStateException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: SkyBlock v2.2.8

Code:

Backtrace:
#0 src/pocketmine/level/Level(613): pocketmine\level\Level->close()
#1 src/pocketmine/Server(1061): pocketmine\level\Level->unload(boolean )
#2 plugins/SkyBlock_v2.2.8/src/room17/SkyBlock/isle/IsleManager(148): pocketmine\Server->unloadLevel(pocketmine\level\Level object)
#3 plugins/SkyBlock_v2.2.8/src/room17/SkyBlock/isle/Isle(377): room17\SkyBlock\isle\IsleManager->closeIsle(room17\SkyBlock\isle\Isle object)
#4 plugins/SkyBlock_v2.2.8/src/room17/SkyBlock/session/SessionManager(92): room17\SkyBlock\isle\Isle->tryToClose()
#5 plugins/SkyBlock_v2.2.8/src/room17/SkyBlock/session/SessionListener(50): room17\SkyBlock\session\SessionManager->closeSession(pocketmine\Player object)
#6 src/pocketmine/plugin/MethodEventExecutor(38): room17\SkyBlock\session\SessionListener->onQuit(pocketmine\event\player\PlayerQuitEvent object)
#7 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(room17\SkyBlock\session\SessionListener object, pocketmine\event\player\PlayerQuitEvent object)
#8 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerQuitEvent object)
#9 src/pocketmine/Player(3483): pocketmine\event\Event->call()
#10 src/pocketmine/Player(3217): pocketmine\Player->close(string , string transfer, boolean )
#11 plugins/SlashServer-master/src/SmartLord/SlashServer/Main(131): pocketmine\Player->transfer(string networkbe.mcpe.eu, integer 19134)
#12 plugins/SlashServer-master/src/SmartLord/SlashServer/TransferTask(28): SmartLord\SlashServer\Main->transferPlayer(pocketmine\Player object, string Freebuild, string networkbe.mcpe.eu, integer 19134)
#13 src/pocketmine/scheduler/TaskHandler(159): SmartLord\SlashServer\TransferTask->onRun(integer 22448)
#14 src/pocketmine/scheduler/TaskScheduler(199): pocketmine\scheduler\TaskHandler->run(integer 22448)
#15 src/pocketmine/plugin/PluginManager(688): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 22448)
#16 src/pocketmine/Server(2587): pocketmine\plugin\PluginManager->tickSchedulers(integer 22448)
#17 src/pocketmine/Server(2342): pocketmine\Server->tick()
#18 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
#19 src/pocketmine/Server(1784): pocketmine\Server->start()
#20 src/pocketmine/PocketMine(250): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/leo/skyblock/, string /home/leo/skyblock/plugins/)
#21 (1): require(string phar:///home/leo/skyblock/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.6.4 [Protocol 332]
Git commit: af90e18b18372849c5946be00620a9891f28ebb1
uname -a: Linux FactionBE 3.10.0-862.11.6.vz7.71.8 #1 SMP Fri Aug 31 18:21:42 MSK 2018 x86_64
PHP Version: 7.2.13
Zend version: 3.2.0
OS : Linux, linux`

**Comment by GiantQuartz** [comment]
Thanks for the report

**Comment by GiantQuartz** [comment]
I have no idea how to reproduce this, could you tell me the exact steps you did to produce it?

**Comment by GiantQuartz** [comment]
d1867e91a4309dd12191de7526b01d3921e74cef should prevent anything like this from happening again.
