### ISSUE TITLE
Teleport back to the main island (world)

### ISSUE THREAD

**Issue by GENEMATOR** [GiantQuartz/SkyBlock#133]
Ok... I created my own island then teleported to it. However, I don't know how to return back to main world on my server! Is there a forum or tutorial pages for this plugin???

**Comment by Shelly7w7** [comment]
Yes. You need a external plugin to teleport back to main spawn. Use EssentialsPE which can be found on poggit.pmmp.io

**Comment by GENEMATOR** [comment]
How about using your essentials 😍
