### ISSUE TITLE
Custom Config

### ISSUE THREAD

**Issue by JGYTVevo** [GiantQuartz/SkyBlock#142]
**_### Please add a config to make this huge amazing skyblock plugin (the best I've tried) so much better

1. Island schematic
2.Island ranking "1 2 3"
3.daily island rewards "Number 1 island of the day gets random rewards"
4.Top island blocks
5.Enable no fall damage or disable (this would help me with my server)_**

**Comment by GiantQuartz** [comment]
Thanks for the suggestion, I will consider it. 

However, I might take a few months to make it a reality as I want to focus on other important aspects now.
