### ISSUE TITLE
Question: Generator Presets

### ISSUE THREAD

**Issue by ver24436** [GiantQuartz/SkyBlock#143]
I wanted to know if there was some command or option to produce our own "Generator Presets" as found in src\room17\SkyBlock\generator\presets

I'm just looking for an easy way I can take a custom island i build and add it as a preset, which players could access using /is create (preset)

If it's not currently possible I think this would be an awesome enhancement for server owners to be able to build an island and run a command like /is generate <preset_name>

Thanks for you time.

**Comment by GiantQuartz** [comment]
I'm afraid not, at the moment, the only way to create a generator preset is by coding it.
