### ISSUE TITLE
Hey! Pls help

### ISSUE THREAD

**Issue by XSlimeX** [GiantQuartz/SkyBlock#146]
Umm.. How i can make other players that are not op to break blocks o their islands etc? Only op can break blocks;-;

**Comment by TehcJS** [comment]
Title your issue "[Feature Request] <New feature name here>" so they know what you want added before they click your issue in the issue list.

**Comment by GiantQuartz** [comment]
Thanks for the suggestion, I will consider it.

However, I might take a few months to implement new features as I want to focus on more important aspects right now.
