### ISSUE TITLE
Too many open files [CRASH]

### ISSUE THREAD

**Issue by ManiakMCPE** [GiantQuartz/SkyBlock#151]
10.08 16:54:10 [Server] Server thread/INFO Preparing world "is-0.60700700 1565456050"
10.08 16:54:10 [Server] Server thread/INFO Reloading blocks due to level is-0.60700700 1565456050 loaded...
10.08 16:54:10 [Server] Server thread/NOTICE Spawn terrain for world "is-0.60700700 1565456050" is being generated in the background
10.08 16:54:12 [Server] Server thread/CRITICAL ErrorException: "touch(): Unable to create file /worlds/is-0.14932300 1565456038/region/r.0.-1.mca because Too many open files" (EXCEPTION) in "src/pocketmine/level/format/io/region/RegionLoader" at line 89
10.08 16:54:12 [Server] Server thread/DEBUG #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[151] touch(): Unable to create file /worlds, string[119] phar:///jar/pocketmine/pocketmine.phar/src/pocketmine/, integer 89, array[1])
10.08 16:54:12 [Server] Server thread/DEBUG #1 src/pocketmine/level/format/io/region/RegionLoader(89): touch(string[92] /worlds/is-0.14932300 1565456038/regio)
10.08 16:54:12 [Server] Server thread/DEBUG #2 src/pocketmine/level/format/io/region/McRegion(349): pocketmine\level\format\io\region\RegionLoader->open()
10.08 16:54:12 [Server] Server thread/DEBUG #3 src/pocketmine/level/format/io/region/McRegion(388): pocketmine\level\format\io\region\McRegion->loadRegion(integer 0, integer -1)
10.08 16:54:12 [Server] Server thread/DEBUG #4 src/pocketmine/level/format/io/BaseLevelProvider(170): pocketmine\level\format\io\region\McRegion->readChunk(integer 0, integer -1)
10.08 16:54:12 [Server] Server thread/DEBUG #5 src/pocketmine/level/Level(2826): pocketmine\level\format\io\BaseLevelProvider->loadChunk(integer 0, integer -1)
10.08 16:54:12 [Server] Server thread/DEBUG #6 src/pocketmine/level/Level(2419): pocketmine\level\Level->loadChunk(integer 0, integer -1, boolean )
10.08 16:54:12 [Server] Server thread/DEBUG #7 src/pocketmine/level/Level(2454): pocketmine\level\Level->getChunk(integer 0, integer -1, boolean )
10.08 16:54:12 [Server] Server thread/DEBUG #8 src/pocketmine/level/generator/PopulationTask(53): pocketmine\level\Level->getAdjacentChunks(integer 0, integer 0)
10.08 16:54:12 [Server] Server thread/DEBUG #9 src/pocketmine/level/Level(3133): pocketmine\level\generator\PopulationTask->__construct(object pocketmine\level\Level, object pocketmine\level\format\Chunk)
10.08 16:54:12 [Server] Server thread/DEBUG #10 src/pocketmine/Player(1052): pocketmine\level\Level->populateChunk(integer 0, integer 0)
10.08 16:54:12 [Server] Server thread/DEBUG #11 src/pocketmine/Player(1833): pocketmine\Player->sendNextChunk()
10.08 16:54:12 [Server] Server thread/DEBUG #12 src/pocketmine/Server(2579): pocketmine\Player->checkNetwork()
10.08 16:54:12 [Server] Server thread/DEBUG #13 src/pocketmine/Server(2345): pocketmine\Server->tick()
10.08 16:54:12 [Server] Server thread/DEBUG #14 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
10.08 16:54:12 [Server] Server thread/DEBUG #15 src/pocketmine/Server(1784): pocketmine\Server->start()
10.08 16:54:12 [Server] Server thread/DEBUG #16 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[43] /, string[51] /plugins/)
10.08 16:54:12 [Server] Server thread/DEBUG #17 src/pocketmine/PocketMine(299): pocketmine\server()
10.08 16:54:12 [Server] Server thread/DEBUG #18 (1): require(string[94] phar:///jar/pocketmine/pocketmine.phar/src/pocketmine/)
10.08 16:54:12 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
10.08 16:54:12 [Server] INFO Fatal error: Uncaught ErrorException: include(phar:///jar/pocketmine/pocketmine.phar/vendor/composer/../pocketmine/spl/LogLevel.php): failed to open stream: phar error: Cannot open phar archive "/jar/pocketmine/pocketmine.phar" for reading in phar:///jar/pocketmine/pocketmine.phar/vendor/composer/ClassLoader.php:444
10.08 16:54:12 [Server] INFO Stack trace:
10.08 16:54:12 [Server] INFO #0 phar:///jar/pocketmine/pocketmine.phar/vendor/composer/ClassLoader.php(444): pocketmine\utils\Utils::errorExceptionHandler(2, 'include(phar://...', 'phar:///home/mi...', 444, Array)
10.08 16:54:12 [Server] INFO #1 phar:///jar/pocketmine/pocketmine.phar/vendor/composer/ClassLoader.php(444): include()
10.08 16:54:12 [Server] INFO #2 phar:///jar/pocketmine/pocketmine.phar/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('phar:///home/mi...')
10.08 16:54:12 [Server] INFO #3 [internal function]: Composer\Autoload\ClassLoader->loadClass('LogLevel')
10.08 16:54:12 [Server] INFO #4 phar:///jar/pocketmine/pocketmine.pha in phar:///jar/pocketmine/pocketmine.phar/vendor/composer/ClassLoader.php on line 444
10.08 16:54:12 [Server] Server thread/CRITICAL RuntimeException: "Could not create Crash Dump" (EXCEPTION) in "src/pocketmine/CrashDump" at line 116
10.08 16:54:12 [Server] Server thread/DEBUG #0 src/pocketmine/Server(2265): pocketmine\CrashDump->__construct(object pocketmine\Server)
10.08 16:54:12 [Server] Server thread/DEBUG #1 src/pocketmine/Server(2248): pocketmine\Server->crashDump()
10.08 16:54:12 [Server] Server thread/DEBUG #2 src/pocketmine/Server(1786): pocketmine\Server->exceptionHandler(object ErrorException)
10.08 16:54:12 [Server] Server thread/DEBUG #3 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[43] /, string[51] /plugins/)
10.08 16:54:12 [Server] Server thread/DEBUG #4 src/pocketmine/PocketMine(299): pocketmine\server()
10.08 16:54:12 [Server] Server thread/DEBUG #5 (1): require(string[94] phar:///jar/pocketmine/pocketmine.phar/src/pocketmine/)
10.08 16:54:12 [Server] Server thread/CRITICAL Could not create crash dump: Could not create Crash Dump

**Comment by GiantQuartz** [comment]
I don't have enough information to understand what is going on here, when you have time, open another issue explaining step by step how to reproduce this issue.
