### ISSUE TITLE
Tried to close a world which is already closed

### ISSUE THREAD

**Issue by ManiakMCPE** [GiantQuartz/SkyBlock#152]
11.08 23:42:55 [Server] Server thread/INFO Unloading world "is-0.02223400 1565399727"
11.08 23:42:55 [Server] Server thread/CRITICAL InvalidStateException: "Tried to close a world which is already closed" (EXCEPTION) in "src/pocketmine/level/Level" at line 480
11.08 23:42:55 [Server] Server thread/DEBUG #0 src/pocketmine/level/Level(625): pocketmine\level\Level->close()
11.08 23:42:55 [Server] Server thread/DEBUG #1 src/pocketmine/Server(1062): pocketmine\level\Level->unload(boolean )
11.08 23:42:55 [Server] Server thread/DEBUG #2 plugins/101-SkyBlock-b7780/src/room17/SkyBlock/isle/IsleManager(148): pocketmine\Server->unloadLevel(object pocketmine\level\Level)
11.08 23:42:55 [Server] Server thread/DEBUG #3 plugins/101-SkyBlock-b7780/src/room17/SkyBlock/isle/Isle(377): room17\SkyBlock\isle\IsleManager->closeIsle(object room17\SkyBlock\isle\Isle)
11.08 23:42:55 [Server] Server thread/DEBUG #4 plugins/101-SkyBlock-b7780/src/room17/SkyBlock/session/SessionManager(92): room17\SkyBlock\isle\Isle->tryToClose()
11.08 23:42:55 [Server] Server thread/DEBUG #5 plugins/101-SkyBlock-b7780/src/room17/SkyBlock/session/SessionListener(50): room17\SkyBlock\session\SessionManager->closeSession(object pocketmine\Player)
11.08 23:42:55 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/MethodEventExecutor(38): room17\SkyBlock\session\SessionListener->onQuit(object pocketmine\event\player\PlayerQuitEvent)
11.08 23:42:55 [Server] Server thread/DEBUG #7 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(object room17\SkyBlock\session\SessionListener, object pocketmine\event\player\PlayerQuitEvent)
11.08 23:42:55 [Server] Server thread/DEBUG #8 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerQuitEvent)
11.08 23:42:55 [Server] Server thread/DEBUG #9 src/pocketmine/Player(3498): pocketmine\event\Event->call()
11.08 23:42:55 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/RakLibInterface(122): pocketmine\Player->close(object pocketmine\lang\TranslationContainer, string[17] client disconnect)
11.08 23:42:55 [Server] Server thread/DEBUG #11 vendor/pocketmine/raklib/src/server/ServerHandler(131): pocketmine\network\mcpe\RakLibInterface->closeSession(string[21] 108.239.129.167 57060, string[17] client disconnect)
11.08 23:42:55 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
11.08 23:42:55 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
11.08 23:42:55 [Server] Server thread/DEBUG #14 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
11.08 23:42:55 [Server] Server thread/DEBUG #15 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
11.08 23:42:55 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2348): pocketmine\snooze\SleeperHandler->sleepUntil(double 1565566975.0107)
11.08 23:42:55 [Server] Server thread/DEBUG #17 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
11.08 23:42:55 [Server] Server thread/DEBUG #18 src/pocketmine/Server(1784): pocketmine\Server->start()
11.08 23:42:55 [Server] Server thread/DEBUG #19 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[43] /, string[51] /plugins/)
11.08 23:42:55 [Server] Server thread/DEBUG #20 src/pocketmine/PocketMine(299): pocketmine\server()
11.08 23:42:55 [Server] Server thread/DEBUG #21 (1): require(string[94] phar:///jar/pocketmine/pocketmine.phar/src/pocketmine/)
11.08 23:42:55 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
11.08 23:42:55 [Server] Server thread/EMERGENCY Please upload the "/crashdumps/Sun_Aug_11-23.42.55-UTC_2019.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by GiantQuartz** [comment]
Hello, which version of SkyBlock are you using?

**Comment by ManiakMCPE** [comment]
The version from February. I don't know if you've fixed it since then.

**Comment by GiantQuartz** [comment]
Yes, I fixed it yesterday, you might want to download the latest development version as the update hasn't been released on Poggit yet.

https://poggit.pmmp.io/ci/GiantQuartz/SkyBlock/SkyBlock
