### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by thehexmor** [GiantQuartz/SkyBlock#157]
hey . update this plugin ! add some more features 
for example 
1- level
2- biome 
3- gui and ui
4- custom island generator (design the island by the server Owner)
5- real size like minecraft java edition for example 100 * 100 - 200 * 200 - 300 * 300 (i mean build limit)

**Comment by thehexmor** [comment]
is tops
random ore and update generators

**Comment by GAMESTER90** [comment]
https://poggit.pmmp.io/p/OreGen/1.1.3

You can install this to fix that ore generation issue, as for the other stuff you are out of your mind haha, 

What I really do want however is to be able to generate costum islands somehow if the player makes big "roads" I guess and goes far if you know what I mean...
