### ISSUE TITLE
Cant visit other islands

### ISSUE THREAD

**Issue by ElectroGamesYT** [GiantQuartz/SkyBlock#165]
People cannot viit other peoples islands and everyones islands is called Null

**Comment by GianC-Dev** [comment]
Opposite player maybe off visit's

**Comment by GiantQuartz** [comment]
Could you try to reproduce this issue on a server without other plugins?

**Comment by GiantQuartz** [comment]
I'm just going to close this for now. If you find a way to reproduce it, please, open another issue.
