### ISSUE TITLE
Error with Version 2.3.3

### ISSUE THREAD

**Issue by MrSquid1yt** [GiantQuartz/SkyBlock#167]
Hello Developer of SkyBlock!
I have the Version 2.3.3 Latest and I have this error in my Console when I join my server 
[Server thread/CRITICAL]: TypeError: "Argument 5 passed to room17\SkyBlock\isle\IsleManager::openIsle() must be an instance of pocketmine\level\Level, null given, called in phar:///home/minecraft/plugins/SkyBlock (2).phar/src/room17/SkyBlock/provider/json/JSONProvider.php on line 105" (EXCEPTION) in "plugins/SkyBlock (2).phar/src/room17/SkyBlock/isle/IsleManager" at line 137
Please help my I have so many fun with SkyBlock :)
Thanks for Help

**Comment by GiantQuartz** [comment]
It looks like your island was removed from world's folder. I will have to make sure this is an actual bug before fixing it. Until then, you might want to consider resetting your progress by removing your SkyBlock's data from the folder "users" (which is a hacky, but effective way to fix your problem).
