### ISSUE TITLE
Question: Islands

### ISSUE THREAD

**Issue by SlowClubStudios** [GiantQuartz/SkyBlock#169]
Will you be able to have Island Upgrades, prestiges or leaderboards like PC Skyblocks?  Thanks in advanced.

**Comment by GiantQuartz** [comment]
I would love to add those features, but I don't have enough time nor motivation to keep working on this project, however, I will try to maintain and keep the plugin up-to-date for a long time

**Comment by SlowClubStudios** [comment]
What if I'd pay for the extra features?

**Comment by GiantQuartz** [comment]
That could work — This is my email:
abnermevid@gmail.com
Send me a message with all the conditions.
