### ISSUE TITLE
Question 2: Worlds

### ISSUE THREAD

**Issue by SlowClubStudios** [GiantQuartz/SkyBlock#170]
did u ever fix the issues where u crate a island it floods the world folder with them? like does it now come in it own folder or something?

**Comment by GiantQuartz** [comment]
I don't know what you're talking about here, this plugin has never had an issue with world folders.

**Comment by SlowClubStudios** [comment]
![Annotation 2020-02-19 185309](https://user-images.githubusercontent.com/60865222/74887525-24013b80-5349-11ea-996e-3ee450bfc9b2.png)

when many people create island it floods the actual world folder, anyway u can add its own folder in the world folder for it?

**Comment by iZeaoGamer** [comment]
or better still - create islands in the same world like some java skyblock plugins.
