### ISSUE TITLE
How to edit the new island?

### ISSUE THREAD

**Issue by ThatsSpike** [GiantQuartz/SkyBlock#171]
So I was looking through the commands and couldn't find a way to edit the island design. Is it possible or?

**Comment by GiantQuartz** [comment]
At the moment, there's no way to do that without coding. If you have time, you could try to create your own island generator, it's not really hard. Take a look at how the generators are made [here](https://github.com/GiantQuartz/SkyBlock/tree/master/src/room17/SkyBlock/island/generator/presets).
