### ISSUE TITLE
For some reason it doesn't allow non-operated status players interact/break on their skyblock island...

### ISSUE THREAD

**Issue by TotallyNotKHM9** [GiantQuartz/SkyBlock#172]
I'm not sure if this is a multi-plugin error but I am having some troubles with the plugin... the plugin does not allow non-operated players to not be able to break blocks or interact with them. And I cannot get anything from the console.

**Comment by GiantQuartz** [comment]
SkyBlock's 3.0.0 haven't been tested, so it might be a bug. I have to test it.

If you're using any previous version such as 2.x or the Poggit's version, then it is very unlikely to be caused by me and it is probably caused by another plugin.
