### ISSUE TITLE
Patch Your plugin, it make crash servers

### ISSUE THREAD

**Issue by GamingFR91** [GiantQuartz/SkyBlock#187]
<h3>Patch Your Plugin and no exceptions because it make crash servers's PocketMine with plugins and if it corrupt , all these servers will go blame you and your plugin will be reported to Github and Poggit PMMP</h3>
Then patch your plugin

**Comment by GiantQuartz** [comment]
wtf?

**Comment by GamingFR91** [comment]
Pfffff... Lazybones

**Comment by Abi2005** [comment]
Oh, this is one interesting thread 🧐

**Comment by IceCruelStuff** [comment]
@GamingFR91 Did you seriously liked your own comment?
