### ISSUE TITLE
Dev #156 error

### ISSUE THREAD

**Issue by AbisGameryt** [GiantQuartz/SkyBlock#191]
[19:52:44] [Server thread/CRITICAL]: ErrorException: "Undefined index: L" (EXCEPTION) in "plugins/SkyBlock_dev-155.phar/src/GiantQuartz/SkyBlock/SkyBlockSettings" at line 76
edit : It also keeps killing my server.
Please Fix This. Thx !

**Comment by jaylac2000** [comment]
DEV 157 error

[Server thread/CRITICAL]: Error: "Call to undefined method GiantQuartz\SkyBlock\session\Session::hasIsle()" (EXCEPTION) in "C:/Users/Administrator/Documents/mc servers/TRY/plugin_data/ScoreHud/addons/SkyBlockAddon" at line 48

**Comment by GiantQuartz** [comment]
@AbisGameryt Please, update your settings file. If you don't know how, just delete it, that should be enough for SkyBlock to create a new and valid settings file.

@jaylac2000 That's not a SkyBlock issue, an outdated plugin is using SkyBlock incorrectly.
