### ISSUE TITLE
Delete an empty island without a master

### ISSUE THREAD

**Issue by junxiesky** [GiantQuartz/SkyBlock#192]
When my server runs for a period of time, there are a lot of empty island worlds without masters.
I need a command to delete them.

**Comment by GiantQuartz** [comment]
I'm well aware of this problem, it's a known design defect. Fixing it would imply completely breaking backwards compatibility for hundreds (potentially thousands) of servers that use this plugin. This plugin works just fine as is, fixing this is not worth the hassle.
