### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jaylac2000** [GiantQuartz/SkyBlock#193]
make it so islands only "prepare" / load when user signs in

[19:00:53] [Server thread/INFO]: Preparing world "is-0.48936800 1584663555"
[19:00:53] [Server thread/INFO]: Preparing world "is-0.63174500 1584582206"

I only put 2 rather than the whole list lol. 

unload the world when the user signs out

**Comment by jaylac2000** [comment]
when player deletes their island it also deletes world folder from worlds_data folder to have less worlds on the server

**Comment by GiantQuartz** [comment]
> unload the world when the user signs out

That's exactly how SkyBlock works right now.
