### ISSUE TITLE
incompatibility with the scorehud addon

### ISSUE THREAD

**Issue by Centoller** [GiantQuartz/SkyBlock#194]
I have a skyblock server in which I use its plugin supported by another ui plugin, I also have the scorehud plugin that has an addon for the scorehud, unfortunately I can't make it compatible or fix the errors it has, could you help me so that Is it compatible with your skyblock plugin 

Scorehud Addon your plugin Skyblock: https://github.com/JackMD/ScoreHud-Addons

**Comment by GiantQuartz** [comment]
I took a quick look at the source and this might be the problem:
```php
use room17\SkyBlock\session\BaseSession as SkyBlockSession;
use room17\SkyBlock\SkyBlock;
```
There's a problem with the imports, it's using the old namespaces. Just update them to the current ones and the addon might work just fine.

**Comment by Centoller** [comment]
I change the namespaces
`use GiantQuartz\SkyBlock\session\BaseSession as SkyBlockSession;`
`use GiantQuartz\SkyBlock\SkyBlock;` 

but it keeps showing error, this is the error

`Error: Call to undefined method 
    room17\SkyBlock\session\Session
    ::hasIsle()
File: /home/container/plugin_data
    /ScoreHud/addons/SkyBlockAddon
Line: 48

Type: Error`

**Comment by GiantQuartz** [comment]
This means the plugin is still using the namespace `room17\SkyBlock\session\Session` somewhere,  you should find it and change it to the correct one. Once you get it working, I encourage you to open your own fork with the changes you made so other people can use your work.

**Comment by GiantQuartz** [comment]
And by the way, the method `hasIsle()` was renamed to `hasIsland()`.
