### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by PsychoPE** [GiantQuartz/SkyBlock#196]
Hey, QuiverlyRivalry said you do commissions could I dm you on discord for further details?

**Comment by GiantQuartz** [comment]
My discord is GiantQuartz#1199, you must be on either PocketMine or MiNET's discord channel too or it won't let you message me.

**Comment by PsychoPE** [comment]
Could you send me the PMMP server?

**Comment by GiantQuartz** [comment]
https://discord.gg/xCNrhDd
