### ISSUE TITLE
What happened

### ISSUE THREAD

**Issue by jesdicaDomo** [GiantQuartz/SkyBlock#2]
[Server thread/CRITICAL]: Could not tick level "Home": Call to a member function spawnToAll() on null

How do I fix it?

**Comment by GiantQuartz** [comment]
This is probably not a SkyBlock's issue, anyway, I can try to figure what's happening if you tell me the steps you did to produce this error, your OS version (and PocketMine version) and your SkyBlock version.

**Comment by GiantQuartz** [comment]
This is probably not a SkyBlock's issue, anyway, I can try to figure what's happening if you tell me the steps you did to produce this error, your OS version (and PocketMine version) and your SkyBlock version.
