### ISSUE TITLE
Permissions per Multiworld

### ISSUE THREAD

**Issue by suerion** [GiantQuartz/SkyBlock#202]
Hello, i need a little bit help,

how i can add permissions for multiworld and skyblock? all my players jump in the /is create, then they are creative, because the main world is creativ

**Comment by GiantQuartz** [comment]
You have to either code it yourself or find a plugin that changes the player game mode depending on the world they are

**Comment by suerion** [comment]
And what is with permissions? Pureperms and so permission tools don‘t add the new world to the groups.
