### ISSUE TITLE
How change the floor

### ISSUE THREAD

**Issue by WhatsAppps** [GiantQuartz/SkyBlock#203]
How to change the floor?

**Comment by GiantQuartz** [comment]
The floor of what? An island?

**Comment by WhatsAppps** [comment]
Change the void to the  lava or all?

Pada tanggal Sab, 13 Jun 2020 23:13, GiantQuartz <notifications@github.com>
menulis:

**Comment by WhatsAppps** [comment]
> The floor of what? An island?

Yes

**Comment by GiantQuartz** [comment]
You'd have to modify the generators yourself with code.

Take a look at the generators here:
https://github.com/GiantQuartz/SkyBlock/tree/stable/src/room17/SkyBlock/island/generator/presets

**Comment by WhatsAppps** [comment]
Where i change

Pada tanggal Sen, 15 Jun 2020 00:02, GiantQuartz <notifications@github.com>
menulis:
