### ISSUE TITLE
Whats is this fix please

### ISSUE THREAD

**Issue by SpacyBenGnu** [GiantQuartz/SkyBlock#204]
![Screenshot_2020-06-15-19-38-30-89](https://user-images.githubusercontent.com/64892710/84653490-17c86c00-af40-11ea-9ba4-e2fc17e4329a.jpg)

**Comment by GiantQuartz** [comment]
For some reason, the generator 'basic' is being registered twice. Did you make any changes to the plugin?

**Comment by SpacyBenGnu** [comment]
Nope sir

**Comment by SpacyBenGnu** [comment]
How please

**Comment by GiantQuartz** [comment]
This isn't a SkyBlock issue and can't be replicated without external plugins.
