### ISSUE TITLE
SkyBlock not working,

### ISSUE THREAD

**Issue by play12mmmm** [GiantQuartz/SkyBlock#206]
**Hello, my name is Play and i own a server thats about to go live, it cant go live as the skyblock plugin dosent work, i'v tryed re-installing it and still dosent, i have a custom coded UI for it and its a seprete plugin that i think has nothing to do with it because i'v tried to do the same! ** **_verison: 1.14.60_**

**Comment by GiantQuartz** [comment]
There's nothing I can do if you don't specify the reason it doesn't work and the steps you took to produce that result.
