### ISSUE TITLE
/is go bug

### ISSUE THREAD

**Issue by ShadowMCX** [GiantQuartz/SkyBlock#214]
So when i create an island its fine but if I leave and rejoin and do /is go, then it gives me this error

[Server thread/CRITICAL]: Error: "Call to a member function broadcastPacketToViewers() on null" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 1186

**Comment by GiantQuartz** [comment]
I can't reproduce this issue. Do you still have this problem? Which version of SkyBlock were you using?

**Comment by ShadowMCX** [comment]
Yes im still having the same issue but its only on my test server tho

**Comment by GiantQuartz** [comment]
I'm assuming that this is probably not a SkyBlock issue.
