### ISSUE TITLE
Re-new? :d

### ISSUE THREAD

**Issue by NycuRO** [GiantQuartz/SkyBlock#22]
@GiantAmethyst You coming back? :D

**Comment by andreskomet** [comment]
I'm back, but I won't update this project :')

**Comment by NycuRO** [comment]
@andreskomet Ok, can you create one new or translate @larrythecoder plugin to php :D

**Comment by andreskomet** [comment]
@NycuRO I just saw his plugin, it's almost a java port of this one, so why "translate it to php" if I can just update this? Anyway, I'm very busy with my own network, so I don't have time to update this project.
