### ISSUE TITLE
Console error on /skyblock create

### ISSUE THREAD

**Issue by optimusprime338** [GiantQuartz/SkyBlock#24]
24.06 08:45:46 [Server] Server thread/CRITICAL Could not execute asynchronous task PopulationTask: Task crashed
24.06 08:45:46 [Server] Asynchronous Worker #1 thread/CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::setBiomeColor()" (EXCEPTION) in "/SkyBlock.phar/src/SkyBlock/generator/generators/BasicIsland" at line 85
24.06 08:45:46 [Server] Server thread/CRITICAL Could not execute asynchronous task PopulationTask: Task crashed
24.06 08:45:46 [Server] Server thread/CRITICAL Could not execute asynchronous task PopulationTask: Task crashed
24.06 08:45:46 [Server] Server thread/CRITICAL Could not execute asynchronous task PopulationTask: Task crashed
24.06 08:45:46 [Server] Server thread/CRITICAL Could not execute asynchronous task PopulationTask: Task crashed
24.06 08:45:46 [Server] Server thread/CRITICAL Could not execute asynchronous task PopulationTask: Task crashed
24.06 08:45:46 [Server] Server thread/CRITICAL Could not execute asynchronous task PopulationTask: Task crashed
24.06 08:45:46 [Server] Server thread/CRITICAL Could not execute asynchronous task PopulationTask: Task crashed
24.06 08:45:46 [Server] Server thread/CRITICAL Could not execute asynchronous task PopulationTask: Task crashed
24.06 08:45:46 [Server] Server thread/CRITICAL TypeError: "Argument 2 passed to pocketmine\tile\Tile::createTile() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in phar:///plugins/SkyBlock.phar/src/SkyBlock/skyblock/SkyBlockManager.php on line 52" (EXCEPTION) in "/src/pocketmine/tile/Tile" at line 87
24.06 08:45:46 [Server] Server thread/CRITICAL Unhandled exception executing command 'skyblock create' in skyblock: Argument 2 passed to pocketmine\tile\Tile::createTile() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in phar:///plugins/SkyBlock.phar/src/SkyBlock/skyblock/SkyBlockManager.php on line 52
24.06 08:45:46 [Server] Asynchronous Worker #1 thread/CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::setBiomeColor()" (EXCEPTION) in "/SkyBlock.phar/src/SkyBlock/generator/generators/BasicIsland" at line 85
24.06 08:45:46 [Server] Asynchronous Worker #2 thread/CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::setBiomeColor()" (EXCEPTION) in "/SkyBlock.phar/src/SkyBlock/generator/generators/BasicIsland" at line 85
24.06 08:45:46 [Server] Asynchronous Worker #1 thread/CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::setBiomeColor()" (EXCEPTION) in "/SkyBlock.phar/src/SkyBlock/generator/generators/BasicIsland" at line 85
24.06 08:45:46 [Server] Asynchronous Worker #2 thread/CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::setBiomeColor()" (EXCEPTION) in "/SkyBlock.phar/src/SkyBlock/generator/generators/BasicIsland" at line 85
24.06 08:45:46 [Server] Asynchronous Worker #2 thread/CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::setBiomeColor()" (EXCEPTION) in "/SkyBlock.phar/src/SkyBlock/generator/generators/BasicIsland" at line 85
24.06 08:45:46 [Server] Asynchronous Worker #2 thread/CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::setBiomeColor()" (EXCEPTION) in "/SkyBlock.phar/src/SkyBlock/generator/generators/BasicIsland" at line 85
24.06 08:45:46 [Server] Asynchronous Worker #1 thread/CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::setBiomeColor()" (EXCEPTION) in "/SkyBlock.phar/src/SkyBlock/generator/generators/BasicIsland" at line 85
24.06 08:45:46 [Server] Asynchronous Worker #1 thread/CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::setBiomeColor()" (EXCEPTION) in "/SkyBlock.phar/src/SkyBlock/generator/generators/BasicIsland" at line 85

**Comment by GiantQuartz** [comment]
[This](https://github.com/GiantQuartz/SkyBlock/commit/bfdd2e3856be91648b57cf2ec4c73da0dd40f390) commit fixed this issue.
