### ISSUE TITLE
/skyblock remove

### ISSUE THREAD

**Issue by NycuRO** [GiantQuartz/SkyBlock#3]
/skyblock remove not work correct.

This command show me /skyblock remove {name}.

I'm enter my name and say isn't my island. Why?

....

You can create /skyblock remove without {name} ?
For remove skyblock island :)

**Comment by NycuRO** [comment]
@GiantQuartz

**Comment by GiantQuartz** [comment]
Hello, @NycuRO.
"Remove" isn't a command to delete your islands, it's a command to kick someone from your island team.

To remove your island you should use "disband" or "reset" (Remember: You'll need to wait 10 minutes to create your island before use disband, so I suggest you use reset if you want a create a new one).

Thank you for reporting.

**Comment by NycuRO** [comment]
@GiantQuartz Thank you for speed answer and big thanks because you created this plugin!

You can edit generation of island and add achievments? :) and level island? :)

**Comment by GiantQuartz** [comment]
@NycuRO What kind of achievements? If you want, you can open a new issue with all your ideas, and if they're enough good I'll work on they.
