### ISSUE TITLE
 What happened

### ISSUE THREAD

**Issue by jesdicaDomo** [GiantQuartz/SkyBlock#4]
[Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to Return value of pocketmine\level\Level::getProvider() must implement interface pocketmine\level\format\LevelProvider, null returned

**Comment by GiantQuartz** [comment]
Please, explain as well your problem or I won't be able to do nothing.

When this happen? (and how)
What's the output message?
Did you update to SkyBlock 0.1.7?

**Comment by jesdicaDomo** [comment]
I'm updating my update to SkyBlock 0.1.7?

**Comment by jesdicaDomo** [comment]
Server outages in Island of Lost

**Comment by GiantQuartz** [comment]
What? @jesdicaDomo
