### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by NycuRO** [GiantQuartz/SkyBlock#5]
I have a TODO for skyblock:

1. Achievments and level island ( from pc ) . If you have a more blocks on island , island have + in level.
Island start with level 1.

And achievments: E.g. If you have 64 cobblestone in inventory , use command /skyblock achievements and show one list of skyblock achievments.

Use e.g. /skyblock achievments miner , and for 64 cobblestone give 5 obsidian or other.

2. Nether generator. You can add this?

3. Cobblestone generator have all items create : Item::COBBLESTONE or Item::REDSTONE_ORE or Item::DIAMOND_ORE or Item::GOLD_ORE or Item::IRON_ORE or Item::LAPIS_ORE or Item::COAL_ORE or Item::EMERALD_ORE

If lava is placed on water, get this blocks. 

If i have more todo,i'm added here. @GiantQuartz

**Comment by Skull3x** [comment]
This is very interesting, if this TODO is agreed to I would be more than happy to help

**Comment by GiantQuartz** [comment]
@NycuRO This is going to be added in _SkyBlock 0.2.0_.

@Skull3x You are free to contribute, all kind of help is accepted. I'm going to open a new branch for SkyBlock 0.2.0, you can open your pull requests there (not in the main branch, please).

**Comment by Skull3x** [comment]
Okay, aweosme! :smiley:

**Comment by GiantQuartz** [comment]
@NycuRO the "generator" is already implemented, the next

**Comment by Skull3x** [comment]
![image](https://cloud.githubusercontent.com/assets/15986189/18938811/5a50ead8-85c9-11e6-97f2-617dacc4f8b4.png)

I'll be adding some of these features to your SkyBlock

**Comment by Skull3x** [comment]
Sorry if it took me a while, I'm still developing these features. I am almost done! :smiley:
