### ISSUE TITLE
Suggestion: Schematics

### ISSUE THREAD

**Issue by NycuRO** [GiantQuartz/SkyBlock#7]
I have one idee for generation.

You can create islands with paste schematics. I have one epic schematics for islands . Two members island . shore island and epic. 

You can create generation of schematics for 50x50 blocks. And nether again 50x50 for have all island one map ,not get 10000 maps for server 💃 
You can create @GiantQuartz  ? :)
If you need schematics, speak me :)

And i can help :)

**Comment by Skull3x** [comment]
@NycuRO this would truly be Interesting

**Comment by NycuRO** [comment]
@Skull3x All skyblock plugins from pc use this method

**Comment by Skull3x** [comment]
@NycuRO I am very aware of this feature :)

**Comment by NycuRO** [comment]
@Skull3x You have telegram or gitter for speak you more?
