### ISSUE TITLE
Block count still no good

### ISSUE THREAD

**Issue by isoz** [GiantQuartz/SkyBlock#89]
Block count still not good, this time not on restart, but for example in a cobble generator, every time the user mines the cobble it goes down but it doesn't go up when a new one spawns... This doesn't seem like a very good system maybe implementing it the way it is right now was not a very good idea among other problems in relation to it... Getting complaints from players every day.

Isn't there a way to count the blocks in the world instead of being based on player mining or placing?

**Comment by Shelly7w7** [comment]
FIXXXXX

**Comment by Xenophilicy** [comment]
isoz Who uses block count? Is that information even useful on SkyBlock? Not trying to sound rude or anything, I just can't wrap my head around what purpose this would serve.

**Comment by isoz** [comment]
@Xenophilicy the size of your island is determined by how many blocks are in it... users like to know how many blocks left to be able to upgrade their island... play proper skyblock on PC and you'll understand

**Comment by Xenophilicy** [comment]
@isoz ah right, sorry. I'm a developer, not a player. Thanks for the clarification though.

**Comment by isoz** [comment]
Not a player either, I run servers but I guess it's my job to understand how things work.

**Comment by Xenophilicy** [comment]
@isoz you make a good point, but you do have to give him credit however, for the amazing implementation of all the other features. The benefits sort of outweigh the downs.

**Comment by GiantQuartz** [comment]
I apologize for the time it took me to fix this problem, lately I have had too many projects to work on.

Let me know if there are any errors related to this again.
