### ISSUE TITLE
Island creating cooldown

### ISSUE THREAD

**Issue by MrNoob6969** [GiantQuartz/SkyBlock#94]
Players keep making new island and delete it again and again.
If you can add an island creating cooldown that would be cool.
It will be very helpful.

**Comment by GiantQuartz** [comment]
How long do you think the cooldown should last?

**Comment by MrNoob6969** [comment]
1 or 2h

**Comment by Xenophilicy** [comment]
> How long do you think the cooldown should last?

Could you eventually add an element to enable/disable the cool down, and also make the duration adjustable in the config.yml possibly?
