### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by LeoBdt** [GiantQuartz/SkyBlock#96]
hello could you try to find a way to make your plugin work with slapper ? 

it's says "use this command in game"

**Comment by Jackaboi18** [comment]
> hello could you try to find a way to make your plugin work with slapper ?
> 
> it's says "use this command in game"

do slapper edit <id> addcommand rca {player} is help (or what ever command you want it to run)

**Comment by LeoBdt** [comment]
but i want to make it works with is create ; join

**Comment by LeoBdt** [comment]
omg that's work thank you :)
