### ISSUE TITLE
ASK increase size island

### ISSUE THREAD

**Issue by ilyasafr** [GiantQuartz/SkyBlock#97]
how to increase size island?

**Comment by Shelly7w7** [comment]
hello, you can increase island size by placing blocks, e.g place 10k blcoks to upgrade your island to small.

**Comment by Xenophilicy** [comment]
> hello, you can increase island size by placing blocks, e.g place 10k blcoks to upgrade your island to small.

I think he/she is talking about size in terms of generation of the islands beforehand. Also, you're a contributor, shouldn't you be refraining from smart aleck comments like that?
