### ISSUE TITLE
Add support for schematics

### ISSUE THREAD

**Issue by Jackaboi18** [GiantQuartz/SkyBlock#98]
please make it so we can set custom islands

**Comment by Shelly7w7** [comment]
Sounds good tbh, in other way you can also make generators if you know how to code

**Comment by ver24436** [comment]
I like the idea. It'd be cool if there was a way to load/use schematics.

**Comment by GiantQuartz** [comment]
There will be soon! @ver24436

**Comment by GiantQuartz** [comment]
This has great benefits, but a very big contra: The new version that implemented the schematics would not be compatible with the previous islands, I'm going to close this.
